### ISSUE TITLE
大佬 失效了

### ISSUE THREAD

**Issue by michealzh** [8pig/jetbrains-crack#1]

**Comment by SoulOfMe** [comment]
同样失效，今天早上过来发现gg了。卸载重装了还是激活不了

**Comment by 8pig** [comment]
软件版本  系统

**Comment by 8pig** [comment]
> 同样失效，今天早上过来发现gg了。卸载重装了还是激活不了

软件版本  系统

**Comment by michealzh** [comment]
PhpStorm 2020.2.2
Build #PS-202.7319.77, built on September 23, 2020
Subscription is active until November 19, 2020
Runtime version: 11.0.8+10-b944.31 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.15.7
GC: ParNew, ConcurrentMarkSweep
Memory: 725M
Cores: 4
Registry: run.processes.with.pty=TRUE

**Comment by 8pig** [comment]
> PhpStorm 2020.2.2
> Build #PS-202.7319.77, built on September 23, 2020
> Subscription is active until November 19, 2020
> Runtime version: 11.0.8+10-b944.31 x86_64
> VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
> macOS 10.15.7
> GC: ParNew, ConcurrentMarkSweep
> Memory: 725M
> Cores: 4
> Registry: run.processes.with.pty=TRUE
好了 重新安装
